# Generated by Django 2.2.14 on 2021-09-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210919_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.AddField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True),
        ),
    ]
